DROP DATABASE IF EXISTS bamazonDB;

CREATE DATABASE bamazonDB;

USE bamazonDB;


CREATE TABLE items (
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  Product VARCHAR(100) NOT NULL,
  Department VARCHAR(100),
  Price INTEGER(11),
  Stock INTEGER(11),
  PRIMARY KEY (id)
);

SELECT * FROM items;
